spring:
  application:
    name: course-service
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:changeme}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/edtech_course_service?useSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:changeme}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
course:
  user-service:
    authorization-token: ${USER_SERVICE_AUTH_TOKEN:changeme}
server:
  port: 8081
