spring:
  application:
    name: course-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/edtech_course_service?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
course:
  user-service:
    authorization-token: Bearer TODO_REPLACE_WITH_REQUEST_HEADER
server:
  port: 8081
